---
- name: Install http
  hosts: all
  gather_facts: false
  tasks:
  - name: Install http package
    yum:
        name: httpd
        state: latest
  - name: Start the service
    service:
        name: httpd
        state: started
  - name: Create file
    copy:
         content: basic http webpage
         dest: "/var/www/html/index.html"
  - name: firewall service
    firewalld:
         service: http
         permanent: true
         immediate: true
         state: enabled




