---
- name: Install httpd and start service
  hosts: all
  gather_facts: false
  tasks:
  - name: Install httpd
    yum:
       name: httpd
       state: present
  - name: Service httpd 
    service:
       name: httpd
       state: started
